# ABOUTME: Shell script testing workflow - template for custom test execution
name: Run Tests

on:
  pull_request:
    branches:
      - master
      - main

jobs:
  test:
    name: Run Test Suite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          # TODO: Add any required dependencies
          # Example: sudo apt-get install -y specific-tool

      - name: Run all tests
        run: |
          # TODO: Adapt to your test framework
          # Example: cd tests && ./run_tests.sh
          echo "TODO: Configure test execution"
          exit 1

      - name: Verify tests passed
        run: |
          echo "✅ All tests passed successfully"
          echo ""
          echo "Per CLAUDE.md Section 3: TDD is MANDATORY"
          echo "All features must have tests before merging"
