# ABOUTME: Validates all commit messages follow conventional commit format using centralized reusable workflow
name: Commit Format

on:
  pull_request:
    branches:
      - master
      - main

jobs:
  check-commit-format:
    uses: maxrantil/.github/.github/workflows/conventional-commit-check-reusable.yml@main
    with:
      base-branch: 'master'  # TODO: Change to 'main' if using main branch
