# ABOUTME: Runs pre-commit hooks in CI (catches bypassed hooks)
name: Pre-commit Validation

on:
  pull_request:
    branches:
      - master
      - main

jobs:
  run-pre-commit:
    uses: maxrantil/.github/.github/workflows/pre-commit-check-reusable.yml@master
